from .base import CaseTypeKnowledge, CaseFact, OffenseLevel, Defense

TEXAS_DWI = CaseTypeKnowledge(
    case_type="dwi",
    display_name="Texas DWI (Driving While Intoxicated)",
    jurisdiction="Texas",
    description="Driving While Intoxicated under Texas Penal Code Title 10, Chapter 49",
    statutes=[
        "Tex. Penal Code § 49.01 — Definitions",
        "Tex. Penal Code § 49.04 — DWI",
        "Tex. Penal Code § 49.045 — DWI with Child Passenger",
        "Tex. Penal Code § 49.07 — Intoxication Assault",
        "Tex. Penal Code § 49.08 — Intoxication Manslaughter",
        "Tex. Penal Code § 49.09 — Enhanced Offenses (Repeat DWI)",
    ],
    facts=[
        # --- Priority 1: Critical for case evaluation ---
        CaseFact(
            key="arrest_date",
            question="When were you arrested or pulled over?",
            priority=1,
            category="context",
        ),
        CaseFact(
            key="bac_level",
            question="Do you know what your blood alcohol concentration (BAC) was? If they tested you, they may have told you a number.",
            priority=1,
            category="classification",
            options=["unknown", "below 0.08", "0.08-0.14", "0.15 or higher", "refused test"],
        ),
        CaseFact(
            key="prior_dwi_count",
            question="Have you ever been charged with or convicted of DWI before? If so, how many times?",
            priority=1,
            category="classification",
            options=["0", "1", "2", "3+"],
        ),
        CaseFact(
            key="accident_involved",
            question="Was there a car accident or collision involved in this incident?",
            priority=1,
            category="severity",
            options=["yes", "no"],
        ),
        CaseFact(
            key="injuries",
            question="Were there any injuries to anyone — yourself, passengers, or anyone else?",
            priority=1,
            category="severity",
            follow_up_condition={"accident_involved": "yes"},
            options=["none", "minor", "serious", "fatal"],
        ),
        # --- Priority 2: Important details ---
        CaseFact(
            key="minor_passenger",
            question="Was anyone under 15 years old in the vehicle with you?",
            priority=2,
            category="severity",
            options=["yes", "no"],
        ),
        CaseFact(
            key="how_stopped",
            question="What was the reason the officer pulled you over? Do you know why they stopped you?",
            priority=2,
            category="defense",
        ),
        CaseFact(
            key="field_sobriety_tests",
            question="Did the officer ask you to do any roadside tests, like walking in a line or standing on one leg?",
            priority=2,
            category="defense",
            options=["yes", "no", "unsure"],
        ),
        CaseFact(
            key="chemical_test_type",
            question="Did they do a breath test, a blood draw, or did you refuse testing?",
            priority=2,
            category="defense",
            options=["breath", "blood", "both", "refused", "none"],
        ),
        CaseFact(
            key="blood_draw_warrant",
            question="If they drew blood, did they get a warrant first, or did you consent?",
            priority=2,
            category="defense",
            follow_up_condition={"chemical_test_type": "blood"},
            options=["warrant", "consent", "unsure", "forced"],
        ),
        CaseFact(
            key="open_container",
            question="Were there any open alcoholic beverages in the vehicle?",
            priority=2,
            category="severity",
            options=["yes", "no"],
        ),
        CaseFact(
            key="county",
            question="What county were you in when this happened?",
            priority=2,
            category="context",
        ),
        # --- Priority 3: Helpful details ---
        CaseFact(
            key="miranda_rights",
            question="Were you read your Miranda rights (right to remain silent, right to an attorney)?",
            priority=3,
            category="defense",
            options=["yes", "no", "unsure"],
        ),
        CaseFact(
            key="cdl_holder",
            question="Do you hold a commercial driver's license (CDL)?",
            priority=3,
            category="context",
            options=["yes", "no"],
        ),
        CaseFact(
            key="currently_bonded",
            question="Have you been released on bond? Do you have a court date set?",
            priority=3,
            category="context",
        ),
        CaseFact(
            key="alr_hearing_requested",
            question="Have you requested an ALR hearing? You only have 15 days from the arrest to request one — this is about keeping your license.",
            priority=3,
            category="procedural",
            options=["yes", "no", "unsure", "did not know"],
        ),
        CaseFact(
            key="officer_body_cam",
            question="Do you know if the officer had a body camera or dash camera running?",
            priority=3,
            category="defense",
            options=["yes", "no", "unsure"],
        ),
    ],
    offense_levels=[
        OffenseLevel(
            name="DWI — 1st Offense",
            classification="Class B Misdemeanor",
            jail_range="72 hours to 180 days",
            fine_range="Up to $2,000",
            license_impact="90 to 365 day suspension",
            conditions="BAC ≥ 0.08, no priors, no enhancements",
        ),
        OffenseLevel(
            name="DWI — 1st Offense (BAC ≥ 0.15)",
            classification="Class A Misdemeanor",
            jail_range="Up to 1 year",
            fine_range="Up to $4,000",
            license_impact="90 to 365 day suspension",
            conditions="BAC ≥ 0.15, no priors",
        ),
        OffenseLevel(
            name="DWI — 2nd Offense",
            classification="Class A Misdemeanor",
            jail_range="30 days to 1 year",
            fine_range="Up to $4,000",
            license_impact="180 days to 2 year suspension",
            conditions="One prior DWI conviction",
        ),
        OffenseLevel(
            name="DWI — 3rd+ Offense",
            classification="3rd Degree Felony",
            jail_range="2 to 10 years (TDCJ)",
            fine_range="Up to $10,000",
            license_impact="180 days to 2 year suspension",
            conditions="Two or more prior DWI convictions",
        ),
        OffenseLevel(
            name="DWI with Child Passenger",
            classification="State Jail Felony",
            jail_range="180 days to 2 years (state jail)",
            fine_range="Up to $10,000",
            license_impact="180 days suspension",
            conditions="Passenger under 15 years old",
        ),
        OffenseLevel(
            name="Intoxication Assault",
            classification="3rd Degree Felony",
            jail_range="2 to 10 years (TDCJ)",
            fine_range="Up to $10,000",
            license_impact="180 days to 2 year suspension",
            conditions="Caused serious bodily injury while intoxicated",
        ),
        OffenseLevel(
            name="Intoxication Manslaughter",
            classification="2nd Degree Felony",
            jail_range="2 to 20 years (TDCJ)",
            fine_range="Up to $10,000",
            license_impact="180 days to 2 year suspension",
            conditions="Caused death while intoxicated",
        ),
    ],
    common_defenses=[
        Defense(
            name="Illegal Traffic Stop",
            description="Officer lacked reasonable suspicion to initiate the stop. If the stop itself was unlawful, all evidence obtained afterward may be suppressed.",
            strength_indicator="strong",
            required_facts=["how_stopped"],
        ),
        Defense(
            name="Improper Field Sobriety Tests",
            description="Officer did not follow NHTSA standardized procedures for administering field sobriety tests, or conditions (weather, terrain, footwear) affected results.",
            strength_indicator="moderate",
            required_facts=["field_sobriety_tests"],
        ),
        Defense(
            name="Breathalyzer Reliability",
            description="The breath testing device was improperly calibrated, not maintained per schedule, or the operator was not certified.",
            strength_indicator="moderate",
            required_facts=["chemical_test_type"],
        ),
        Defense(
            name="Blood Draw Without Warrant",
            description="Blood was drawn without a valid warrant or voluntary consent, violating the 4th Amendment. Evidence may be suppressed.",
            strength_indicator="strong",
            required_facts=["blood_draw_warrant"],
        ),
        Defense(
            name="Rising BAC",
            description="Alcohol was still being absorbed at the time of driving — BAC at the time of testing was higher than at the actual time of driving.",
            strength_indicator="moderate",
            required_facts=["bac_level", "arrest_date"],
        ),
        Defense(
            name="No Probable Cause for Arrest",
            description="Officer did not have sufficient probable cause to arrest for DWI. Nervousness, bloodshot eyes alone, or minor driving errors may not be enough.",
            strength_indicator="moderate",
            required_facts=["how_stopped", "field_sobriety_tests"],
        ),
        Defense(
            name="Medical Condition",
            description="A medical condition (diabetes, GERD, neurological disorder) mimicked signs of intoxication or affected chemical test results.",
            strength_indicator="moderate",
            required_facts=[],
        ),
        Defense(
            name="Miranda Violation",
            description="Statements made during custodial interrogation without Miranda warnings may be suppressed. Does not affect the DWI charge itself but can exclude damaging admissions.",
            strength_indicator="weak",
            required_facts=["miranda_rights"],
        ),
        Defense(
            name="Chain of Custody Issues",
            description="Blood sample was improperly stored, labeled, or transported, raising questions about contamination or tampering.",
            strength_indicator="moderate",
            required_facts=["chemical_test_type"],
        ),
    ],
    take_signals=[
        "First offense with no aggravating factors",
        "BAC close to 0.08 threshold",
        "Questionable reason for the traffic stop",
        "Procedural errors during arrest or testing",
        "Blood drawn without warrant or clear consent",
        "No accident or injuries involved",
        "Client is cooperative and motivated",
        "Field sobriety tests conducted improperly or in poor conditions",
        "Breath test only (no blood confirmation)",
        "Dash/body cam footage may support defense",
    ],
    pass_signals=[
        "Multiple prior DWI convictions with strong prosecution evidence",
        "Intoxication manslaughter with clear evidence and no viable defense",
        "Client is uncooperative, dishonest, or has unrealistic expectations",
        "Overwhelming evidence with no procedural issues to challenge",
        "Client cannot make bond and case is straightforward plea",
    ],
    review_signals=[
        "Second offense but possible procedural defense",
        "Accident involved but injuries are minor",
        "BAC was high but there are questions about the testing procedure",
        "Client has a CDL (higher stakes, different standards)",
        "ALR hearing deadline approaching or passed",
    ],
    keywords=[
        "dwi", "dui", "drunk driving", "drinking and driving",
        "pulled over", "breathalyzer", "blood alcohol", "bac",
        "intoxicated", "blew", "breath test", "blood draw",
        "open container", "driving while intoxicated",
    ],
)
