from .base import CaseTypeKnowledge, CaseFact, OffenseLevel, Defense

TEXAS_PARKING = CaseTypeKnowledge(
    case_type="parking_ticket",
    display_name="Texas Parking Violations",
    jurisdiction="Texas",
    description="Municipal parking violations in Texas cities, handled in municipal or justice courts.",
    statutes=[
        "Tex. Transportation Code § 681.011 — Parking for Persons with Disabilities",
        "Tex. Transportation Code § 682 — Towing and Booting",
        "Local municipal ordinances (city-specific)",
    ],
    facts=[
        # --- Priority 1: Critical ---
        CaseFact(
            key="ticket_type",
            question="What kind of parking ticket did you receive? For example, expired meter, no parking zone, fire lane, handicap parking, etc.",
            priority=1,
            category="classification",
            options=[
                "expired meter", "no parking zone", "fire lane",
                "handicap violation", "street sweeping", "overtime parking",
                "double parked", "expired registration display",
                "residential permit zone", "other",
            ],
        ),
        CaseFact(
            key="fine_amount",
            question="How much is the fine on the ticket?",
            priority=1,
            category="context",
        ),
        CaseFact(
            key="ticket_date",
            question="When did you receive the ticket?",
            priority=1,
            category="context",
        ),
        CaseFact(
            key="city",
            question="What city was the ticket issued in?",
            priority=1,
            category="context",
        ),
        CaseFact(
            key="already_paid",
            question="Have you already paid the ticket?",
            priority=1,
            category="context",
            options=["yes", "no"],
        ),
        # --- Priority 2: Important ---
        CaseFact(
            key="multiple_tickets",
            question="Do you have multiple unpaid parking tickets? If so, approximately how many and what's the total amount?",
            priority=2,
            category="severity",
        ),
        CaseFact(
            key="warrant_issued",
            question="Has a warrant been issued for any unpaid tickets, or have you received a notice about one?",
            priority=2,
            category="severity",
            options=["yes", "no", "unsure"],
        ),
        CaseFact(
            key="vehicle_booted_towed",
            question="Has your vehicle been booted or towed because of unpaid tickets?",
            priority=2,
            category="severity",
            options=["yes", "no"],
        ),
        CaseFact(
            key="signage_visible",
            question="Was the parking signage clearly visible? Could you see signs saying you couldn't park there?",
            priority=2,
            category="defense",
            options=["yes clearly marked", "no signs visible", "signs were blocked or unclear", "unsure"],
        ),
        CaseFact(
            key="handicap_details",
            question="Do you have a valid disabled parking placard or plate? Was it displayed at the time?",
            priority=2,
            category="defense",
            follow_up_condition={"ticket_type": "handicap violation"},
            options=["have valid placard, was displayed", "have valid placard, forgot to display", "no placard", "placard was expired"],
        ),
        CaseFact(
            key="already_contested",
            question="Have you already tried to contest the ticket? What happened?",
            priority=2,
            category="context",
            options=["yes", "no"],
        ),
        # --- Priority 3: Helpful ---
        CaseFact(
            key="photo_evidence",
            question="Do you have any photos of the parking situation — the signage, your vehicle's location, or the meter?",
            priority=3,
            category="defense",
            options=["yes", "no"],
        ),
        CaseFact(
            key="meter_malfunction",
            question="If this was a meter violation, was the meter working properly?",
            priority=3,
            category="defense",
            follow_up_condition={"ticket_type": "expired meter"},
            options=["working", "broken/malfunctioning", "unsure"],
        ),
        CaseFact(
            key="registration_hold",
            question="Have you been unable to renew your vehicle registration because of unpaid tickets?",
            priority=3,
            category="severity",
            options=["yes", "no", "unsure"],
        ),
    ],
    offense_levels=[
        OffenseLevel(
            name="Standard Parking Violation",
            classification="Civil/Municipal Infraction",
            jail_range="None (civil matter)",
            fine_range="$25 — $250 (varies by city)",
            conditions="Expired meter, overtime, no parking zone, etc.",
        ),
        OffenseLevel(
            name="Handicap Parking Violation",
            classification="Misdemeanor",
            jail_range="None for first offense (possible for repeat)",
            fine_range="$500 — $1,250+",
            conditions="Parking in a disabled space without valid placard/plate",
        ),
        OffenseLevel(
            name="Fire Lane Violation",
            classification="Municipal Infraction",
            jail_range="None",
            fine_range="$50 — $500 (varies by city)",
            conditions="Parking in a designated fire lane",
        ),
        OffenseLevel(
            name="Accumulated Unpaid Tickets",
            classification="Municipal Warrants",
            jail_range="Possible arrest on warrant",
            fine_range="Original fines + late fees + warrant fees (can reach thousands)",
            conditions="Multiple unpaid tickets with failure to appear",
        ),
    ],
    common_defenses=[
        Defense(
            name="Missing or Obscured Signage",
            description="Parking restriction signs were not posted, were blocked by foliage, or were otherwise not reasonably visible to drivers.",
            strength_indicator="strong",
            required_facts=["signage_visible"],
        ),
        Defense(
            name="Malfunctioning Meter",
            description="The parking meter was broken or not accepting payment, making compliance impossible.",
            strength_indicator="strong",
            required_facts=["meter_malfunction"],
        ),
        Defense(
            name="Valid Placard Not Displayed",
            description="Driver has a valid disabled parking placard but forgot to display it. Can often be dismissed by showing valid placard at hearing.",
            strength_indicator="strong",
            required_facts=["handicap_details"],
        ),
        Defense(
            name="Emergency Circumstances",
            description="Vehicle was parked due to a medical or mechanical emergency.",
            strength_indicator="moderate",
            required_facts=[],
        ),
        Defense(
            name="Incorrect Vehicle Identification",
            description="Ticket was issued to the wrong vehicle — plate number, make, model, or color doesn't match.",
            strength_indicator="strong",
            required_facts=[],
        ),
        Defense(
            name="Ticket Issued in Error",
            description="Meter time had not actually expired, or the vehicle was in a legal spot despite what the ticket says.",
            strength_indicator="moderate",
            required_facts=["photo_evidence"],
        ),
    ],
    take_signals=[
        "Multiple accumulated tickets with warrants — high total fines make representation cost-effective",
        "Handicap violation with valid placard (likely dismissable)",
        "Vehicle booted/towed — urgency and higher financial stakes",
        "Clear signage defense with photo evidence",
        "Commercial vehicle operator with CDL implications",
    ],
    pass_signals=[
        "Single low-value ticket with no defense (e.g., clearly parked at expired meter)",
        "Ticket already paid — nothing to contest",
        "Client just wants to vent, not actually contest",
        "Fine amount is less than even a consultation fee",
    ],
    review_signals=[
        "Moderate accumulated fines ($500-$2,000 range)",
        "Handicap violation without valid placard (harder to defend but high fine)",
        "Client unsure about signage — needs investigation",
        "Registration hold affecting ability to drive legally",
    ],
    keywords=[
        "parking ticket", "parking fine", "parking violation",
        "meter", "towed", "booted", "handicap parking",
        "fire lane", "no parking", "street sweeping",
        "parking warrant", "unpaid ticket", "parking citation",
    ],
)
